### ISSUE TITLE
Invalid store

### ISSUE THREAD

**Issue by MartonDev** [tuks128/G2A-PAY-PHP5-API#9]
Can you tell me why do I keep getting Invalid store error?

**Comment by MartonDev** [comment]
@tuxxx128 please help, i tried everything

**Comment by tuxxx128** [comment]
Hi, which environment dev or production?

**Comment by MartonDev** [comment]
Its in test mode, if you mean that. But it does not work either on test or production

**Comment by MartonDev** [comment]
@tuxxx128

**Comment by MartonDev** [comment]
@tuxxx128 please.

**Comment by MartonDev** [comment]
@tuxxx128

**Comment by tuxxx128** [comment]
sorry, i don't know from head, i'm busy now. Do you have right email for 'merchant email'?

**Comment by ChrisBPB** [comment]
fyi while they display api info when you register it doesn't actually work until you get approved - and you can't use your live api credentials for sandbox, you have to have an account on their actual sandbox website (https://id.test.pay.g2a.com)

**Comment by mohamedaitbella** [comment]
I had the same problem but after i get in touch with the Support they inform me that this problem occurred 
 if the account  is not verified
